services:
  postgres:
    container_name: "todolist"
    image: postgres
    command: postgres -c 'max_connections=1000'
    restart: unless-stopped
    environment:
      - POSTGRES_USER=todoUser
      - POSTGRES_PASSWORD=tod0p4ssw0rd
      - POSTGRES_DB=todolist
    ports:
      - "7890:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./pg-dump:/var/lib/postgresql/dump
  todolist-app:
    build:
      context: .          
      dockerfile: Dockerfile
    container_name: "todolist-app"
    restart: unless-stopped
    ports:
      - "5000:80"
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=localhost;Port=7890;Database=todolist;Username=todoUser;Password=tod0p4ssw0rd;IncludeErrorDetail=true

volumes:
  postgres-data:
    
networks:
  default:
    name: infra
